apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gonewproj
  name: gonewproj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gonewproj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gonewproj
    spec:
      containers:
      - image: kiranbabycontainerrepo.azurecr.io/gonewprojsecret:gonewproj
        name: gonewprojsecret
        resources: {}
      imagePullSecrets: 
      - name: 
status: {}
